version: 2

submodules:
  include: all

build:
  apt_packages:
    - gcc-8
    - g++-8

python:
  system_packages: true
  version: "3.8"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
