version: 2

submodules:
  include: all

build:
  apt_packages:
    - clang-10
    - clang++-10

python:
  system_packages: true
  version: "3.8"
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .

sphinx:
  configuration: docs/conf.py
