version: 2

build:
  apt_packages:
    - gcc-8
    - cmake

python:
  version: "3.10"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
