[build-system]
requires=[
    "setuptools>=42",
    "wheel",
    "ninja; sys_platform != 'win32' and platform_machine != 'arm64'",
    "cmake>=3.12",
    "pep517",
]
build-backend = "setuptools.build_meta"