name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        # platform: [macos-latest]
        # python-version: # ["2.7", "3.5", "3.8", "3.9"]
        python-version: ["3.5", "3.8", "3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Test
        run: cd tests; python -m unittest discover; cd ..

      upload_all:
        name: Upload if release
        needs: [ build_wheels, build_sdist ]
        runs-on: ubuntu-latest
        if: github.event_name == 'release' && github.event.action == 'published'

        steps:
          - uses: actions/setup-python@v2

          - uses: actions/download-artifact@v2
            with:
              name: artifact
              path: dist

          - uses: pypa/gh-action-pypi-publish@v1.4.2
            with:
              user: __token__
              password: ${{ secrets.pypi_token }}
