name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest] # [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.10"] # ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-python@v3.1.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check for Clang
        run: clang++ -v

      - name: Add requirements
        run: python -m pip install --upgrade pip meson ninja wheel setuptools; meson wrap install pybind11

      - name: Build and install
        run: python setup.py develop

      - name: Test
        run: python -m unittest discover tests -t .